import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideHttpClient, withFetch, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/auth/auth.interceptor';
import { provideRouter } from '@angular/router';
import {
  LUCIDE_ICONS,
  LucideIconProvider,
  House,
  Refrigerator,
  ChefHat,
  Wallet,
  ShoppingCart,
  CheckSquare,
  Calendar,
  Zap,
  Bell,
  User,
  Settings,
  LogOut,
  Plus,
  AlertTriangle,
  TrendingUp,
  ArrowRight,
  ArrowLeft,
  ShoppingBasket,
  ClipboardList,
  Info,
  Search,
  Loader,
  Clock,
  Flame,
  Star,
  Shuffle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  X,
  SlidersHorizontal,
  Pencil,
  Shield,
  ShieldCheck,
  Check,
  QrCode,
  Snowflake,
  Package,
  Tag,
  AlertCircle,
  ImageOff,
  Eye,
  EyeOff,
  Mail,
  Lock,
  LockKeyhole,
  Unlock,
  Send,
  // Alacena
  Scan,
  ScanLine,
  SearchX,
  CalendarClock,
  CalendarCheck,
  PackageOpen,
  LockOpen,
  Minus,
  Camera,
  Play,
  Bookmark,
  List,
  BookOpen,
  ChartPie,
  Lightbulb,
  // Hogares / invitaciones
  Ellipsis,
  MailCheck,
  MailOpen,
  CheckCircle,
  CheckCircle2,
  XCircle,
  // Onboarding step 4
  Leaf,
  Target,
  UtensilsCrossed,
  Sprout,
  WheatOff,
  MilkOff,
  // Electrodomesticos
  Coffee,
  Droplet,
  Tv,
  Plug,
  Microwave,
  Trash2,
  WashingMachine,

  // Perfil / Configuracion
  UserRoundPen,
  UserPlus,
  Award,
  Phone,
  Trophy,
  Ban,
  Users,
  CookingPot,
  Blend,
  Cog,
  AirVent,
  Square,
  PlugZap,
  FileText,
  Paperclip,
} from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideHttpClient(withFetch(), withInterceptors([authInterceptor])),
    provideRouter(routes),
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider({
        House,
        Refrigerator,
        ChefHat,
        Wallet,
        ShoppingCart,
        CheckSquare,
        Calendar,
        Zap,
        Bell,
        User,
        Settings,
        LogOut,
        Plus,
        AlertTriangle,
        TrendingUp,
        ArrowRight,
        ArrowLeft,
        ShoppingBasket,
        ClipboardList,
        Info,
        Search,
        Loader,
        Clock,
        Flame,
        Star,
        Shuffle,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        X,
        SlidersHorizontal,
        Pencil,
        Shield,
        ShieldCheck,
        Check,
        QrCode,
        Snowflake,
        Package,
        Tag,
        AlertCircle,
        ImageOff,
        Eye,
        EyeOff,
        Mail,
        Lock,
        LockKeyhole,
        Unlock,
        Send,
        Scan,
        ScanLine,
        SearchX,
        CalendarClock,
        CalendarCheck,
        PackageOpen,
        LockOpen,
        Minus,
        Camera,
        Play,
        Bookmark,
        List,
        BookOpen,
        ChartPie,
        Lightbulb,
        Ellipsis,
        MailCheck,
        MailOpen,
        CheckCircle,
        CheckCircle2,
        XCircle,
        Leaf,
        Target,
        UtensilsCrossed,
        Sprout,
        WheatOff,
        MilkOff,
        Coffee,
        Droplet,
        Tv,
        Plug,
        Microwave,
        Trash2,
        WashingMachine,

        // Perfil / Configuracion
        UserRoundPen,
        UserPlus,
        Award,
        Phone,
        Trophy,
        Ban,
        Users,
        CookingPot,
        Blend,
        Cog,
        AirVent,
        Square,
        PlugZap,
        FileText,
        Paperclip,
      }),
    },
  ],
};
