import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideHttpClient, withFetch, withInterceptors } from '@angular/common/http';
import { authInterceptor } from './core/auth/auth.interceptor';
import { provideRouter } from '@angular/router';
import {
  LUCIDE_ICONS,
  LucideIconProvider,
  House,
  Refrigerator,
  ChefHat,
  Wallet,
  CheckSquare,
  Calendar,
  Zap,
  Bell,
  User,
  Settings,
  LogOut,
  Plus,
  AlertTriangle,
  TrendingUp,
  ArrowRight,
  ShoppingBasket,
  ClipboardList,
  Info,
  Search,
  Clock,
  Flame,
  Star,
  Shuffle,
  ChevronDown,
  X,
  SlidersHorizontal,
  Pencil,
  Shield,
  Check,
  QrCode,
  Snowflake,
  Package,
  Tag,
  AlertCircle,
  Eye,
  EyeOff,
  Mail,
  Lock,
  // Alacena
  Scan,
  ScanLine,
  SearchX,
  CalendarClock,
  CalendarCheck,
  PackageOpen,
  LockOpen,
  Minus,
  Camera,
  // Hogares / invitaciones
  Ellipsis,
  MailCheck,
  MailOpen,
  CheckCircle,
  XCircle,
  // Onboarding step 4
  Leaf,
  Target,
  UtensilsCrossed,
  Sprout,
  WheatOff,
  MilkOff,
  // Electrodomesticos
  Coffee,
  Droplet,
  Tv,
  Plug,

  // Perfil
  UserPlus,
  Award,
  Phone,
  Trophy,
  Ban,
CookingPot,
Blend,
Cog,
AirVent,
Square,
PlugZap,
} from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideHttpClient(withFetch(), withInterceptors([authInterceptor])),
    provideRouter(routes),
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider({
        House,
        Refrigerator,
        ChefHat,
        Wallet,
        CheckSquare,
        Calendar,
        Zap,
        Bell,
        User,
        Settings,
        LogOut,
        Plus,
        AlertTriangle,
        TrendingUp,
        ArrowRight,
        ShoppingBasket,
        ClipboardList,
        Info,
        Search,
        Clock,
        Flame,
        Star,
        Shuffle,
        ChevronDown,
        X,
        SlidersHorizontal,
        Pencil,
        Shield,
        Check,
        QrCode,
        Snowflake,
        Package,
        Tag,
        AlertCircle,
        Eye,
        EyeOff,
        Mail,
        Lock,
        Scan,
        ScanLine,
        SearchX,
        CalendarClock,
        CalendarCheck,
        PackageOpen,
        LockOpen,
        Minus,
        Camera,
        Ellipsis,
        MailCheck,
        MailOpen,
        CheckCircle,
        XCircle,
        Leaf,
        Target,
        UtensilsCrossed,
        Sprout,
        WheatOff,
        MilkOff,
        Coffee,
        Droplet,
        Tv,
        Plug,

        // Perfil
        UserPlus,
        Award,
        Phone,
        Trophy,
        Ban,
CookingPot,
Blend,
Cog,
AirVent,
Square,
PlugZap,
      }),
    },
  ],
};
